"""Create Event, Offer, and EventOffer tables

Revision ID: d12ef65d99b6
Revises: 1a90a4dcde94
Create Date: 2025-10-30 18:51:31.767439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12ef65d99b6'
down_revision: Union[str, Sequence[str], None] = '1a90a4dcde94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('lifetime_hours', sa.Integer(), nullable=True),
        sa.Column('disable_all_campaigns', sa.Boolean(), nullable=True),
        sa.Column('queue_name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_code'), 'events', ['code'], unique=True)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    
    op.create_table('offers',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.Column('target_system', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_code'), 'offers', ['code'], unique=True)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    
    op.create_table('event_offer',
        sa.Column('event_id', sa.String(), nullable=False),
        sa.Column('offer_id', sa.String(), nullable=False),
        sa.Column('delay_minutes', sa.Integer(), nullable=True),
        sa.Column('action_type', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
        sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
        sa.PrimaryKeyConstraint('event_id', 'offer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_offer')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_code'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_code'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
